# Generated by Django 5.1.1 on 2024-10-22 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='group',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animals', models.ManyToManyField(to='app.animal')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.period')),
            ],
        ),
    ]
